import type { QuantityDefinition, QuantityId } from './types'
import { UNIT_SETS } from './units'

function quantity(definition: QuantityDefinition): QuantityDefinition {
  return definition
}

export const quantityDefinitions: QuantityDefinition[] = [
  quantity({
    id: 'frequency',
    label: 'Frequency',
    symbol: 'f',
    kind: 'scalar',
    category: 'AC Basics',
    chapter: '13',
    description: 'Signal frequency.',
    defaultUnitId: 'hz',
    units: [...UNIT_SETS.frequency],
    placeholder: '60',
  }),
  quantity({
    id: 'period',
    label: 'Period',
    symbol: 'T',
    kind: 'scalar',
    category: 'AC Basics',
    chapter: '13',
    description: 'Time for one cycle.',
    defaultUnitId: 's',
    units: [...UNIT_SETS.time],
    placeholder: '0.01667',
  }),
  quantity({
    id: 'cycleCount',
    label: 'Cycle count',
    symbol: 'N',
    kind: 'scalar',
    category: 'AC Basics',
    chapter: '13',
    description: 'Number of cycles.',
    defaultUnitId: 'unitless',
    units: [...UNIT_SETS.unitless],
    placeholder: '3',
  }),
  quantity({
    id: 'elapsedTime',
    label: 'Elapsed time',
    symbol: 't',
    kind: 'scalar',
    category: 'AC Basics',
    chapter: '13',
    description: 'Elapsed time.',
    defaultUnitId: 's',
    units: [...UNIT_SETS.time],
    placeholder: '0.05',
  }),
  quantity({
    id: 'angleDegrees',
    label: 'Angle in degrees',
    symbol: 'deg',
    kind: 'scalar',
    category: 'Utilities',
    chapter: 'Study Guide',
    description: 'Angular measure in degrees.',
    defaultUnitId: 'deg',
    units: [UNIT_SETS.angle[1]],
    placeholder: '45',
  }),
  quantity({
    id: 'angleRadians',
    label: 'Angle in radians',
    symbol: 'rad',
    kind: 'scalar',
    category: 'Utilities',
    chapter: 'Study Guide',
    description: 'Angular measure in radians.',
    defaultUnitId: 'rad',
    units: [UNIT_SETS.angle[0]],
    placeholder: '0.785398',
  }),
  quantity({
    id: 'angularFrequency',
    label: 'Angular frequency',
    symbol: 'omega',
    kind: 'scalar',
    category: 'AC Basics',
    chapter: '13',
    description: 'Angular frequency.',
    defaultUnitId: 'rad_per_s',
    units: [...UNIT_SETS.angularFrequency],
    placeholder: '377',
  }),
  quantity({
    id: 'voltage',
    label: 'Voltage',
    symbol: 'V',
    kind: 'scalar',
    category: 'AC Basics',
    chapter: '13',
    description: 'Scalar voltage magnitude.',
    defaultUnitId: 'v',
    units: [...UNIT_SETS.voltage],
    placeholder: '120',
  }),
  quantity({
    id: 'current',
    label: 'Current',
    symbol: 'I',
    kind: 'scalar',
    category: 'AC Basics',
    chapter: '13',
    description: 'Scalar current magnitude.',
    defaultUnitId: 'a',
    units: [...UNIT_SETS.current],
    placeholder: '2',
  }),
  quantity({
    id: 'resistance',
    label: 'Resistance',
    symbol: 'R',
    kind: 'scalar',
    category: 'AC Basics',
    chapter: '13',
    description: 'Resistance.',
    defaultUnitId: 'ohm',
    units: [...UNIT_SETS.resistance],
    placeholder: '60',
  }),
  quantity({
    id: 'conductance',
    label: 'Conductance',
    symbol: 'G',
    kind: 'scalar',
    category: 'Admittance',
    chapter: '16',
    description: 'Conductance of a resistive branch.',
    defaultUnitId: 's',
    units: [...UNIT_SETS.admittance],
    placeholder: '0.05',
  }),
  quantity({
    id: 'electricForce',
    label: 'Electric force',
    symbol: 'F',
    kind: 'scalar',
    category: 'Electrostatics',
    chapter: '10',
    description: 'Electric force magnitude.',
    defaultUnitId: 'n',
    units: [...UNIT_SETS.force],
    placeholder: '0.36',
  }),
  quantity({
    id: 'electricFieldStrength',
    label: 'Electric field strength',
    symbol: 'E',
    kind: 'scalar',
    category: 'Electrostatics',
    chapter: '10',
    description: 'Electric field strength between plates or around a charge.',
    defaultUnitId: 'v_per_m',
    units: [...UNIT_SETS.electricField],
    placeholder: '60500',
  }),
  quantity({
    id: 'distance',
    label: 'Distance or spacing',
    symbol: 'd',
    kind: 'scalar',
    category: 'Electrostatics',
    chapter: '10',
    description: 'Distance from a point charge or spacing between capacitor plates.',
    defaultUnitId: 'mm',
    units: [...UNIT_SETS.distance],
    placeholder: '0.794',
  }),
  quantity({
    id: 'plateArea',
    label: 'Plate area',
    symbol: 'A',
    kind: 'scalar',
    category: 'Electrostatics',
    chapter: '10',
    description: 'Effective area of the capacitor plates.',
    defaultUnitId: 'cm2',
    units: [...UNIT_SETS.area],
    placeholder: '25.81',
  }),
  quantity({
    id: 'permittivity',
    label: 'Permittivity',
    symbol: 'epsilon',
    kind: 'scalar',
    category: 'Electrostatics',
    chapter: '10',
    description: 'Absolute permittivity of the dielectric.',
    defaultUnitId: 'f_per_m',
    units: [...UNIT_SETS.permittivity],
    placeholder: '2.2125e-9',
  }),
  quantity({
    id: 'relativePermittivity',
    label: 'Relative permittivity',
    symbol: 'eps_r',
    kind: 'scalar',
    category: 'Electrostatics',
    chapter: '10',
    description: 'Dielectric constant relative to free space.',
    defaultUnitId: 'unitless',
    units: [...UNIT_SETS.unitless],
    placeholder: '250',
  }),
  quantity({
    id: 'airCapacitance',
    label: 'Air or vacuum capacitance',
    symbol: 'C0',
    kind: 'scalar',
    category: 'Electrostatics',
    chapter: '10',
    description: 'Capacitance before a dielectric is inserted.',
    defaultUnitId: 'f',
    units: [...UNIT_SETS.capacitance],
    placeholder: '28.8',
  }),
  quantity({
    id: 'dielectricStrength',
    label: 'Dielectric strength',
    symbol: 'Emax',
    kind: 'scalar',
    category: 'Electrostatics',
    chapter: '10',
    description: 'Maximum allowable electric field before breakdown.',
    defaultUnitId: 'v_per_mil',
    units: [...UNIT_SETS.electricField],
    placeholder: '80',
  }),
  quantity({
    id: 'inductiveReactance',
    label: 'Inductive reactance',
    symbol: 'XL',
    kind: 'scalar',
    category: 'Reactance',
    chapter: '14',
    description: 'Inductive reactance.',
    defaultUnitId: 'ohm',
    units: [...UNIT_SETS.resistance],
    placeholder: '18.85',
  }),
  quantity({
    id: 'inductiveSusceptance',
    label: 'Inductive susceptance',
    symbol: 'BL',
    kind: 'scalar',
    category: 'Admittance',
    chapter: '16',
    description: 'Inductive susceptance.',
    defaultUnitId: 's',
    units: [...UNIT_SETS.admittance],
    placeholder: '0.1',
  }),
  quantity({
    id: 'capacitiveReactance',
    label: 'Capacitive reactance',
    symbol: 'XC',
    kind: 'scalar',
    category: 'Reactance',
    chapter: '14',
    description: 'Capacitive reactance.',
    defaultUnitId: 'ohm',
    units: [...UNIT_SETS.resistance],
    placeholder: '530.5',
  }),
  quantity({
    id: 'capacitiveSusceptance',
    label: 'Capacitive susceptance',
    symbol: 'BC',
    kind: 'scalar',
    category: 'Admittance',
    chapter: '16',
    description: 'Capacitive susceptance.',
    defaultUnitId: 's',
    units: [...UNIT_SETS.admittance],
    placeholder: '0.05',
  }),
  quantity({
    id: 'netSusceptance',
    label: 'Net susceptance',
    symbol: 'B',
    kind: 'scalar',
    category: 'Admittance',
    chapter: '16',
    description: 'Net susceptance of the parallel network.',
    defaultUnitId: 's',
    units: [...UNIT_SETS.admittance],
    placeholder: '-0.075',
  }),
  quantity({
    id: 'dvDt',
    label: 'dv/dt',
    symbol: 'dv/dt',
    kind: 'scalar',
    category: 'Capacitors',
    chapter: '10',
    description: 'Rate of change of voltage.',
    defaultUnitId: 'v_per_s',
    units: [...UNIT_SETS.voltageRate],
    placeholder: '250',
  }),
  quantity({
    id: 'diDt',
    label: 'di/dt',
    symbol: 'di/dt',
    kind: 'scalar',
    category: 'Inductors',
    chapter: '11',
    description: 'Rate of change of current.',
    defaultUnitId: 'a_per_s',
    units: [...UNIT_SETS.currentRate],
    placeholder: '5',
  }),
  quantity({
    id: 'magneticFluxRate',
    label: 'dPhi/dt',
    symbol: 'dPhi/dt',
    kind: 'scalar',
    category: 'Inductors',
    chapter: '11',
    description: 'Rate of change of magnetic flux.',
    defaultUnitId: 'wb_per_s',
    units: [...UNIT_SETS.fluxRate],
    placeholder: '0.02',
  }),
  quantity({
    id: 'impedanceMagnitude',
    label: 'Impedance magnitude',
    symbol: '|Z|',
    kind: 'scalar',
    category: 'Impedance',
    chapter: '15',
    description: 'Magnitude of impedance.',
    defaultUnitId: 'ohm',
    units: [...UNIT_SETS.resistance],
    placeholder: '75',
  }),
  quantity({
    id: 'admittanceMagnitude',
    label: 'Admittance magnitude',
    symbol: '|Y|',
    kind: 'scalar',
    category: 'Admittance',
    chapter: '16',
    description: 'Magnitude of admittance.',
    defaultUnitId: 's',
    units: [...UNIT_SETS.admittance],
    placeholder: '0.214',
  }),
  quantity({
    id: 'powerFactor',
    label: 'Power factor',
    symbol: 'pf',
    kind: 'scalar',
    category: 'Power',
    chapter: '14',
    description: 'Power factor.',
    defaultUnitId: 'unitless',
    units: [...UNIT_SETS.unitless],
    placeholder: '0.8',
  }),
  quantity({
    id: 'realPower',
    label: 'Real power',
    symbol: 'P',
    kind: 'scalar',
    category: 'Power',
    chapter: '14',
    description: 'Real power.',
    defaultUnitId: 'w',
    units: [...UNIT_SETS.power],
    placeholder: '960',
  }),
  quantity({
    id: 'peakCurrent',
    label: 'Peak current',
    symbol: 'Im',
    kind: 'scalar',
    category: 'Waveforms',
    chapter: '13',
    description: 'Peak current.',
    defaultUnitId: 'a',
    units: [...UNIT_SETS.current],
    placeholder: '10',
  }),
  quantity({
    id: 'rmsCurrent',
    label: 'RMS current',
    symbol: 'Irms',
    kind: 'scalar',
    category: 'Waveforms',
    chapter: '13',
    description: 'RMS current.',
    defaultUnitId: 'a',
    units: [...UNIT_SETS.current],
    placeholder: '7.07',
  }),
  quantity({
    id: 'peakVoltage',
    label: 'Peak voltage',
    symbol: 'Vm',
    kind: 'scalar',
    category: 'Waveforms',
    chapter: '13',
    description: 'Peak voltage.',
    defaultUnitId: 'v',
    units: [...UNIT_SETS.voltage],
    placeholder: '170',
  }),
  quantity({
    id: 'rmsVoltage',
    label: 'RMS voltage',
    symbol: 'Vrms',
    kind: 'scalar',
    category: 'Waveforms',
    chapter: '13',
    description: 'RMS voltage.',
    defaultUnitId: 'v',
    units: [...UNIT_SETS.voltage],
    placeholder: '120',
  }),
  quantity({
    id: 'inductiveImpedance',
    label: 'Inductor impedance',
    symbol: 'ZL',
    kind: 'complex',
    category: 'Phasors',
    chapter: '14',
    description: 'Inductive impedance as a complex quantity.',
    defaultUnitId: 'ohm',
    units: [...UNIT_SETS.resistance],
    placeholder: '0+18.85j',
  }),
  quantity({
    id: 'capacitiveImpedance',
    label: 'Capacitor impedance',
    symbol: 'ZC',
    kind: 'complex',
    category: 'Phasors',
    chapter: '14/15',
    description: 'Capacitive impedance as a complex quantity.',
    defaultUnitId: 'ohm',
    units: [...UNIT_SETS.resistance],
    placeholder: '0-265.3j',
  }),
  quantity({
    id: 'inductorVoltagePhasor',
    label: 'Inductor voltage phasor',
    symbol: 'VL',
    kind: 'complex',
    category: 'Phasors',
    chapter: '15',
    description: 'Voltage across an inductor.',
    defaultUnitId: 'v',
    units: [...UNIT_SETS.voltage],
    placeholder: '0+188.5j',
  }),
  quantity({
    id: 'capacitorVoltagePhasor',
    label: 'Capacitor voltage phasor',
    symbol: 'VC',
    kind: 'complex',
    category: 'Phasors',
    chapter: '14',
    description: 'Voltage across a capacitor.',
    defaultUnitId: 'v',
    units: [...UNIT_SETS.voltage],
    placeholder: '0-31.8j',
  }),
  quantity({
    id: 'impedanceComplex',
    label: 'Complex impedance',
    symbol: 'Z',
    kind: 'complex',
    category: 'Impedance',
    chapter: '15',
    description: 'Complex impedance.',
    defaultUnitId: 'ohm',
    units: [...UNIT_SETS.resistance],
    placeholder: '40+10j',
  }),
  quantity({
    id: 'admittanceComplex',
    label: 'Complex admittance',
    symbol: 'Y',
    kind: 'complex',
    category: 'Admittance',
    chapter: '16',
    description: 'Complex admittance.',
    defaultUnitId: 's',
    units: [...UNIT_SETS.admittance],
    placeholder: '0.2-0.075j',
  }),
  quantity({
    id: 'netReactance',
    label: 'Net reactance',
    symbol: 'X',
    kind: 'scalar',
    category: 'Impedance',
    chapter: '15',
    description: 'Net reactance XL - XC.',
    defaultUnitId: 'ohm',
    units: [...UNIT_SETS.resistance],
    placeholder: '10',
  }),
  quantity({
    id: 'phaseAngle',
    label: 'Phase angle',
    symbol: 'phi',
    kind: 'scalar',
    category: 'Power',
    chapter: '14',
    description: 'Phase angle.',
    defaultUnitId: 'deg',
    units: [...UNIT_SETS.angle],
    placeholder: '36.87',
  }),
  quantity({
    id: 'waveformPhaseAngle',
    label: 'Waveform phase angle',
    symbol: 'theta',
    kind: 'scalar',
    category: 'Waveforms',
    chapter: '15',
    description: 'Phase angle taken directly from a sine-wave time expression before converting to the textbook phasor convention.',
    defaultUnitId: 'deg',
    units: [...UNIT_SETS.angle],
    placeholder: '-80',
  }),
  quantity({
    id: 'admittanceAngle',
    label: 'Admittance angle',
    symbol: 'thetaY',
    kind: 'scalar',
    category: 'Admittance',
    chapter: '16',
    description: 'Angle of the total admittance.',
    defaultUnitId: 'deg',
    units: [...UNIT_SETS.angle],
    placeholder: '-20.56',
  }),
  quantity({
    id: 'inductance',
    label: 'Inductance',
    symbol: 'L',
    kind: 'scalar',
    category: 'Inductors',
    chapter: '11/14',
    description: 'Inductance.',
    defaultUnitId: 'h',
    units: [...UNIT_SETS.inductance],
    placeholder: '0.05',
  }),
  quantity({
    id: 'capacitance',
    label: 'Capacitance',
    symbol: 'C',
    kind: 'scalar',
    category: 'Capacitors',
    chapter: '10/14',
    description: 'Capacitance.',
    defaultUnitId: 'f',
    units: [...UNIT_SETS.capacitance],
    placeholder: '0.000001',
  }),
  quantity({
    id: 'phasorCurrent',
    label: 'Current phasor',
    symbol: 'I',
    kind: 'complex',
    category: 'Phasors',
    chapter: '15',
    description: 'Current as a complex phasor.',
    defaultUnitId: 'a',
    units: [...UNIT_SETS.current],
    placeholder: '2@-30deg',
  }),
  quantity({
    id: 'phasorSourceVoltage',
    label: 'Source voltage phasor',
    symbol: 'E',
    kind: 'complex',
    category: 'Phasors',
    chapter: '15',
    description: 'Source voltage as a phasor.',
    defaultUnitId: 'v',
    units: [...UNIT_SETS.voltage],
    placeholder: '120@0deg',
  }),
  quantity({
    id: 'resistorVoltagePhasor',
    label: 'Resistor voltage phasor',
    symbol: 'VR',
    kind: 'complex',
    category: 'Phasors',
    chapter: '15',
    description: 'Voltage across a resistor.',
    defaultUnitId: 'v',
    units: [...UNIT_SETS.voltage],
    placeholder: '80+0j',
  }),
  quantity({
    id: 'branchVoltagePhasor',
    label: 'Branch voltage phasor',
    symbol: 'Vx',
    kind: 'complex',
    category: 'Phasors',
    chapter: '15',
    description: 'Voltage across a branch.',
    defaultUnitId: 'v',
    units: [...UNIT_SETS.voltage],
    placeholder: '48+12j',
  }),
  quantity({
    id: 'branchImpedance',
    label: 'Branch impedance',
    symbol: 'Zx',
    kind: 'complex',
    category: 'Phasors',
    chapter: '15',
    description: 'Branch impedance.',
    defaultUnitId: 'ohm',
    units: [...UNIT_SETS.resistance],
    placeholder: '20+5j',
  }),
  quantity({
    id: 'totalImpedance',
    label: 'Total impedance',
    symbol: 'Zt',
    kind: 'complex',
    category: 'Phasors',
    chapter: '15',
    description: 'Total impedance.',
    defaultUnitId: 'ohm',
    units: [...UNIT_SETS.resistance],
    placeholder: '50+10j',
  }),
  quantity({
    id: 'equivalentParallelResistance',
    label: 'Equivalent parallel resistance',
    symbol: 'Rp',
    kind: 'scalar',
    category: 'Equivalent Networks',
    chapter: '15',
    description: 'Parallel resistance equivalent to a series RL combination.',
    defaultUnitId: 'ohm',
    units: [...UNIT_SETS.resistance],
    placeholder: '125',
  }),
  quantity({
    id: 'equivalentParallelInductiveReactance',
    label: 'Equivalent parallel inductive reactance',
    symbol: 'XLp',
    kind: 'scalar',
    category: 'Equivalent Networks',
    chapter: '15',
    description: 'Parallel inductive reactance equivalent to a series RL combination.',
    defaultUnitId: 'ohm',
    units: [...UNIT_SETS.resistance],
    placeholder: '250',
  }),
  quantity({
    id: 'charge',
    label: 'Charge',
    symbol: 'Q',
    kind: 'scalar',
    category: 'Capacitors',
    chapter: '10',
    description: 'Electric charge, including stored plate charge or a point charge.',
    defaultUnitId: 'c',
    units: [...UNIT_SETS.charge],
    placeholder: '0.00012',
  }),
  quantity({
    id: 'parallelCapacitorList',
    label: 'Parallel capacitor list',
    symbol: 'C1..Cn',
    kind: 'scalarList',
    category: 'Capacitors',
    chapter: '10',
    description: 'Comma-separated capacitor values in parallel.',
    defaultUnitId: 'uf',
    units: [...UNIT_SETS.capacitance],
    placeholder: '1, 2.2, 4.7',
  }),
  quantity({
    id: 'seriesCapacitorList',
    label: 'Series capacitor list',
    symbol: 'C1..Cn',
    kind: 'scalarList',
    category: 'Capacitors',
    chapter: '10',
    description: 'Comma-separated capacitor values in series.',
    defaultUnitId: 'uf',
    units: [...UNIT_SETS.capacitance],
    placeholder: '1, 2.2, 4.7',
  }),
  quantity({
    id: 'totalCapacitance',
    label: 'Total capacitance',
    symbol: 'CT',
    kind: 'scalar',
    category: 'Capacitors',
    chapter: '10',
    description: 'Equivalent capacitance.',
    defaultUnitId: 'f',
    units: [...UNIT_SETS.capacitance],
    placeholder: '0.0000079',
  }),
  quantity({
    id: 'timeConstant',
    label: 'Time constant',
    symbol: 'tau',
    kind: 'scalar',
    category: 'Transients',
    chapter: '10/11',
    description: 'RC or RL time constant.',
    defaultUnitId: 's',
    units: [...UNIT_SETS.time],
    placeholder: '0.001',
  }),
  quantity({
    id: 'rcChargingVoltage',
    label: 'RC charging voltage',
    symbol: 'vC(t)',
    kind: 'scalar',
    category: 'Transients',
    chapter: '10',
    description: 'Capacitor charging voltage at time t.',
    defaultUnitId: 'v',
    units: [...UNIT_SETS.voltage],
    placeholder: '3.16',
  }),
  quantity({
    id: 'rcChargingCurrent',
    label: 'RC charging current',
    symbol: 'iC(t)',
    kind: 'scalar',
    category: 'Transients',
    chapter: '10',
    description: 'Capacitor charging current at time t.',
    defaultUnitId: 'a',
    units: [...UNIT_SETS.current],
    placeholder: '0.368',
  }),
  quantity({
    id: 'rcDischargingVoltage',
    label: 'RC discharging voltage',
    symbol: 'vC(t)',
    kind: 'scalar',
    category: 'Transients',
    chapter: '10',
    description: 'Capacitor discharging voltage at time t.',
    defaultUnitId: 'v',
    units: [...UNIT_SETS.voltage],
    placeholder: '3.68',
  }),
  quantity({
    id: 'rcDischargingCurrent',
    label: 'RC discharging current',
    symbol: 'iC(t)',
    kind: 'scalar',
    category: 'Transients',
    chapter: '10',
    description: 'Capacitor discharging current at time t.',
    defaultUnitId: 'a',
    units: [...UNIT_SETS.current],
    placeholder: '0.368',
  }),
  quantity({
    id: 'finalVoltage',
    label: 'Final voltage',
    symbol: 'Vfinal',
    kind: 'scalar',
    category: 'Transients',
    chapter: '10',
    description: 'Final source voltage for charging.',
    defaultUnitId: 'v',
    units: [...UNIT_SETS.voltage],
    placeholder: '5',
  }),
  quantity({
    id: 'storedEnergy',
    label: 'Stored energy',
    symbol: 'W',
    kind: 'scalar',
    category: 'Capacitors',
    chapter: '10',
    description: 'Energy stored by a capacitor.',
    defaultUnitId: 'j',
    units: [...UNIT_SETS.energy],
    placeholder: '0.000072',
  }),
  quantity({
    id: 'rlGrowthCurrent',
    label: 'RL growth current',
    symbol: 'i(t)',
    kind: 'scalar',
    category: 'Transients',
    chapter: '11',
    description: 'Current during RL growth.',
    defaultUnitId: 'a',
    units: [...UNIT_SETS.current],
    placeholder: '0.632',
  }),
  quantity({
    id: 'finalCurrent',
    label: 'Final current',
    symbol: 'Ifinal',
    kind: 'scalar',
    category: 'Transients',
    chapter: '11',
    description: 'Final steady-state current.',
    defaultUnitId: 'a',
    units: [...UNIT_SETS.current],
    placeholder: '1',
  }),
  quantity({
    id: 'inducedVoltage',
    label: 'Induced voltage',
    symbol: 'e',
    kind: 'scalar',
    category: 'Inductors',
    chapter: '11',
    description: 'Induced emf.',
    defaultUnitId: 'v',
    units: [...UNIT_SETS.voltage],
    placeholder: '2',
  }),
  quantity({
    id: 'turnCount',
    label: 'Turns',
    symbol: 'N',
    kind: 'scalar',
    category: 'Inductors',
    chapter: '11',
    description: 'Number of turns.',
    defaultUnitId: 'unitless',
    units: [...UNIT_SETS.unitless],
    placeholder: '100',
  }),
  quantity({
    id: 'complexRectangular',
    label: 'Complex number',
    symbol: 'z',
    kind: 'complex',
    category: 'Utilities',
    chapter: 'Study Guide',
    description: 'Generic complex number in rectangular form.',
    defaultUnitId: 'unitless',
    units: [...UNIT_SETS.unitless],
    placeholder: '3+4j',
  }),
  quantity({
    id: 'polarMagnitude',
    label: 'Polar magnitude',
    symbol: 'r',
    kind: 'scalar',
    category: 'Utilities',
    chapter: 'Study Guide',
    description: 'Magnitude for a polar complex number.',
    defaultUnitId: 'unitless',
    units: [...UNIT_SETS.unitless],
    placeholder: '5',
  }),
  quantity({
    id: 'polarAngle',
    label: 'Polar angle',
    symbol: 'theta',
    kind: 'scalar',
    category: 'Utilities',
    chapter: 'Study Guide',
    description: 'Angle for a polar complex number.',
    defaultUnitId: 'deg',
    units: [...UNIT_SETS.angle],
    placeholder: '53.13',
  }),
  quantity({
    id: 'complexFactorA',
    label: 'Complex factor A',
    symbol: 'z1',
    kind: 'complex',
    category: 'Utilities',
    chapter: 'Study Guide',
    description: 'First factor for complex multiplication.',
    defaultUnitId: 'unitless',
    units: [...UNIT_SETS.unitless],
    placeholder: '2+3j',
  }),
  quantity({
    id: 'complexFactorB',
    label: 'Complex factor B',
    symbol: 'z2',
    kind: 'complex',
    category: 'Utilities',
    chapter: 'Study Guide',
    description: 'Second factor for complex multiplication.',
    defaultUnitId: 'unitless',
    units: [...UNIT_SETS.unitless],
    placeholder: '1-4j',
  }),
  quantity({
    id: 'complexProduct',
    label: 'Complex product',
    symbol: 'z1*z2',
    kind: 'complex',
    category: 'Utilities',
    chapter: 'Study Guide',
    description: 'Product of two complex numbers.',
    defaultUnitId: 'unitless',
    units: [...UNIT_SETS.unitless],
    placeholder: '14-5j',
  }),
  quantity({
    id: 'coilRadius',
    label: 'Coil radius',
    symbol: 'r',
    kind: 'scalar',
    category: 'Coils',
    chapter: '15',
    description: 'Single-layer air-core coil radius.',
    defaultUnitId: 'in',
    units: [...UNIT_SETS.length],
    placeholder: '0.5',
  }),
  quantity({
    id: 'coilLength',
    label: 'Coil length',
    symbol: 'l',
    kind: 'scalar',
    category: 'Coils',
    chapter: '15',
    description: 'Single-layer air-core coil length.',
    defaultUnitId: 'in',
    units: [...UNIT_SETS.length],
    placeholder: '1.2',
  }),
  quantity({
    id: 'coilTurns',
    label: 'Coil turns',
    symbol: 'n',
    kind: 'scalar',
    category: 'Coils',
    chapter: '15',
    description: 'Turns on an air-core coil.',
    defaultUnitId: 'unitless',
    units: [...UNIT_SETS.unitless],
    placeholder: '45',
  }),
]

export const quantityMap = Object.fromEntries(
  quantityDefinitions.map((definition) => [definition.id, definition]),
) as Record<QuantityId, QuantityDefinition>
